## NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
# checking numpy version

np.__version__

'1.21.5'

In [5]:
# ndarray

arr1 = np.array([1,2,3,4,5])

type(arr1)

numpy.ndarray

In [6]:
# using tuple to create numpy

tuple_arr = np.array((1,2,3,4,5))

print(tuple_arr)

[1 2 3 4 5]


# Dimentions in array

### 0-D 

In [7]:
zero_d_arr = np.array(1)

# each value in array is called zero d arr

print(zero_d_arr)

# checking dimention

print(zero_d_arr.ndim)

1
0


### 1-D

In [8]:
one_d_arr = np.array([1,2,3,4,5])

print(one_d_arr)

# checking dimention

print(one_d_arr.ndim)

[1 2 3 4 5]
1


### 2-D 

In [9]:
two_d_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(two_d_arr)

# checking dimention

print(two_d_arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


### 3-D 

In [10]:
three_d_arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                        [[10,11,12],[13,14,15],[16,17,18]]])

print(three_d_arr)

# checking dimention

print(three_d_arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3


### higher dimention 

In [11]:
five_d_arr = np.array([1,2,3,4,5],ndmin=5)

print(five_d_arr)

#checking dimentions

print(five_d_arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


# Indexing

In [12]:
arr = np.array([1, 2, 3, 4])

In [13]:
arr[0]

1

In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [15]:
# Access the element on the first row, second column:
arr[0,1]

2

In [16]:
arr[0][1]

# same results

2

In [17]:
# Access the element on the 2nd row, 5th column:

arr[1][4]

10

In [18]:
# or 

arr[1,4]

10

In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])

In [20]:
# Access the third element of the second array of the first array:

arr[0,1,2]

6

In [21]:
# or 

arr[0][1][2]

6

### negative index

In [22]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [23]:
# Print the last element from the 2nd dim:

arr[1,-1]

10

In [24]:
# or 

arr[1][-1]

10

# NumPy Array Slicing 

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [26]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [27]:
# it includes start index but exclude end index

arr[2:6]

array([3, 4, 5, 6])

In [28]:
# Slice elements from index 4 to the end of the array:

arr[4:]

array([5, 6, 7])

In [29]:
# Slice elements from the beginning to index 4 (not included):

arr[:4]

array([1, 2, 3, 4])

### Negative Slicing

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [31]:
arr[-4:-1]

array([4, 5, 6])

### STEP

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [33]:
arr[1:6:2]

array([2, 4, 6])

## Slicing 2-D Arrays

In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [35]:
arr[1,1:4]

array([7, 8, 9])

In [36]:
# From both elements, return index 2:

arr[0:2,2]

array([3, 8])

In [37]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

# NumPy Data Types

In [38]:
arr = np.array([1, 2, 3, 4])

## Checking the Data Type of an Array

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr = np.array(['apple', 'banana', 'cherry'])

In [41]:
arr.dtype

dtype('<U6')

### Creating Arrays With a Defined Data Type

In [42]:
arr = np.array([1,2,3,4], dtype='S')

In [43]:
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [44]:
arr.dtype

dtype('S1')

In [45]:
arr = np.array([1, 2, 3, 4], dtype='i4')

In [46]:
arr.dtype

dtype('int32')

In [47]:
# What if value can be canoverted ?

# it will raise ValueError

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

### Converting Data Type on Existing Arrays

In [48]:
arr = np.array([1.1, 2.1, 3.1])

In [49]:
arr_new = arr.astype('i')

In [50]:
arr_new

array([1, 2, 3], dtype=int32)

### Change data type from float to integer by using int as parameter value:

In [51]:
arr = np.array([1.1, 2.1, 3.1])

In [52]:
new_arr = arr.astype(int)

In [53]:
new_arr.dtype

dtype('int64')

In [54]:
# bool


arr = np.array([1, 0, 3])

new_arr = arr.astype(bool)

In [55]:
new_arr

array([ True, False,  True])

# NumPy Array Copy vs View

In [56]:
arr = np.array([1,2,3,4,5])

In [57]:
x = arr.copy()

In [58]:
arr[0] = 42

In [59]:
print(x)

[1 2 3 4 5]


In [60]:
print(arr)

[42  2  3  4  5]


In [61]:
## View()

arr = np.array([1, 2, 3, 4, 5])

In [62]:
x = arr.view()

In [63]:
x[0] = 31

In [64]:
print(arr)

[31  2  3  4  5]


In [65]:
print(x)

[31  2  3  4  5]


### Check if Array Owns its Data

In [66]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

In [67]:
print(x.base)

None


In [68]:
print(y.base)

[1 2 3 4 5]


# Numpy Shape

#### The shape of an array is the number of elements in each dimension

In [69]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [70]:
arr.shape

(2, 4)

#### The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

In [71]:
arr = np.array([1, 2, 3, 4], ndmin=5)

In [72]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [73]:
arr.shape

(1, 1, 1, 1, 4)

# NumPy Array Reshaping

## Reshape From 1-D to 2-D

In [74]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [75]:
# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [76]:
# dimention

arr.reshape(4,3).ndim

2

## Reshape From 1-D to 3-D

In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#### Convert the following 1-D array with 12 elements into a 3-D array.

#### The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:



In [78]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [79]:
# Can We Reshape Into any Shape?

In [80]:
# Yes, as long as the elements required for reshaping are equal in both shapes.

In [81]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
arr_new = arr.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

# Unknown Dimension

In [83]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
arr_new = arr.reshape(2,2,-1)

In [85]:
arr_new

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.



In [86]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [87]:
arr_new = arr.reshape(-1)

In [88]:
arr_new

array([1, 2, 3, 4, 5, 6])

### Iterating Arrays
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [89]:
# Iterate on the elements of the following 1-D array:

arr = np.array([1, 2, 3])

In [90]:
for x in arr:
    print(x)

1
2
3


### Iterating 2-D Arrays
In a 2-D array it will go through all the rows.



In [91]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [92]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [93]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


### Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.

In [94]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [95]:
for x in arr:
    for y in x:
        for z in y:
            print(z, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [96]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [97]:
# nditer()

for x in np.nditer(arr):
    print(x, end=' ')

1 2 3 4 5 6 7 8 

### Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [98]:
arr = np.array([1, 2, 3])

In [99]:
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


## Iterating With Different Step Size

In [100]:
# Iterate through every scalar element of the 2D array skipping 1 element:

In [101]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [102]:
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


### Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [103]:
arr = np.array([1, 2, 3])

In [104]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [105]:
## Enumerate on following 2D array's elements:

In [106]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [107]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Join

In [108]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [109]:
arr = np.concatenate((arr1,arr2))

# f axis is not explicitly passed, it is taken as 0.

In [110]:
arr

array([1, 2, 3, 4, 5, 6])

In [111]:
# Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

In [112]:
arr = np.concatenate((arr1,arr2),axis=1)

In [113]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Joining Arrays Using Stack Functions

In [114]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [115]:
arr = np.stack((arr1,arr2),axis=1)

In [116]:
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [117]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [118]:
arr = np.hstack((arr1, arr2))

In [119]:
arr

array([1, 2, 3, 4, 5, 6])

In [120]:
# Stacking Along Columns

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

In [121]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

In [123]:
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# SPLIT

Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [124]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [125]:
arr_new = np.array_split(arr, 3)

In [126]:
arr_new

[array([1, 2]), array([3, 4]), array([5, 6])]

In [127]:
# If the array has less elements than required, it will adjust from the end accordingly.

arr = np.array([1, 2, 3, 4, 5, 6])

arr_new = np.array_split(arr, 4)

In [128]:
arr_new

[array([1, 2]), array([3, 4]), array([5]), array([6])]

##### Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [129]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr_new = np.array_split(arr, 3)

In [130]:
arr_new

[array([1, 2]), array([3, 4]), array([5, 6])]

In [131]:
arr_new[0][1]

2

## Splitting 2-D Arrays

In [132]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

In [133]:
arr_new = np.array_split(arr,3)

In [134]:
arr_new

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# NumPy Searching Arrays

In [135]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [136]:
x = np.where(arr == 4)

In [137]:
x

(array([3, 5, 6]),)

In [138]:
# Find the indexes where the values are even:

x = np.where(arr % 2 == 0)

In [139]:
x

(array([1, 3, 5, 6]),)

## Search Sorted

#### The searchsorted() method is assumed to be used on sorted arrays.

In [140]:
arr = np.array([6, 7, 8, 9])

In [141]:
x = np.searchsorted(arr, 7)

In [142]:
x

1

# NumPy Sorting Arrays

In [143]:
arr = np.array([3, 2, 0, 1])

In [144]:
np.sort(arr)

array([0, 1, 2, 3])

## Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [145]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

In [146]:
np.sort(arr)

array([[2, 3, 4],
       [0, 1, 5]])

# NumPy Filter Array

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [147]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

In [148]:
arr_new = arr[x]

In [149]:
arr_new

array([41, 43])

# Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [150]:
arr = np.array([41, 42, 43, 44])

In [151]:
arr_filter = []

for x in arr:
    if x > 41:
        arr_filter.append(True)
    else:
        arr_filter.append(False)

In [152]:
arr_filter

[False, True, True, True]