In [1]:
from numpy import random

In [2]:
x = random.randint(100)

In [3]:
x

47

Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

In [4]:
x = random.rand()

In [5]:
x

0.5428482763561326

### Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

Integers
The #randint() method takes a #size parameter where you can specify the shape of an array.



In [8]:
# Generate a 1-D array containing 5 random integers from 0 to 100:


x = random.randint(100, size=5)

In [9]:
x

array([38,  2, 46, 29, 11])

In [12]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x = random.randint(100, size = (3,5))

In [13]:
x

array([[ 3, 53, 37, 81,  7],
       [19, 78, 66, 49, 52],
       [29, 63, 90, 27,  5]])

In [14]:
# The rand() method also allows you to specify the shape of the array.

In [15]:
x = random.rand(5)

In [16]:
x

array([0.80016939, 0.23952482, 0.10635815, 0.9398011 , 0.39579864])

In [17]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:

x = random.rand(5,4)

In [18]:
x

array([[0.63011696, 0.19525758, 0.46841623, 0.00305626],
       [0.083097  , 0.24431843, 0.32927692, 0.67015068],
       [0.9522202 , 0.00374228, 0.33423405, 0.16819105],
       [0.30746857, 0.3954617 , 0.44706764, 0.07408748],
       [0.28050714, 0.75999648, 0.25503136, 0.91881917]])

### Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [19]:
x = random.choice([1,2,3,4,5])

In [20]:
x

2

### The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.



In [21]:
x = random.choice([1,2,3,4],size=(3,5))

In [22]:
x

array([[4, 2, 2, 1, 3],
       [1, 4, 3, 2, 3],
       [4, 2, 4, 3, 4]])

# What is Data Distribution?
Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.



## Random Distribution

### A random distribution is a set of random numbers that follow a certain probability density function.



#### Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.

# Example

Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

In [23]:
x = random.choice([3,5,7,9], p=[0.1, 0.3, 0.6, 0.0], size=100)

In [24]:
x

array([7, 7, 3, 7, 7, 7, 5, 7, 7, 7, 7, 7, 5, 7, 7, 7, 7, 7, 7, 5, 5, 7,
       7, 5, 5, 7, 7, 5, 7, 7, 5, 7, 5, 7, 5, 7, 7, 5, 3, 5, 7, 7, 5, 7,
       7, 7, 7, 3, 7, 5, 7, 7, 7, 7, 5, 7, 3, 5, 7, 5, 5, 3, 7, 5, 7, 3,
       7, 7, 7, 5, 5, 5, 7, 5, 7, 7, 5, 5, 7, 3, 7, 7, 7, 5, 3, 5, 7, 7,
       7, 7, 7, 7, 7, 5, 3, 7, 7, 7, 3, 5])

# Random Permutations of Elements

A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: shuffle() and permutation().


### Shuffling Arrays
Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

In [25]:
from numpy import random

import numpy as np

In [26]:
arr = np.array([1,2,3,4,5])

In [29]:
random.shuffle(arr)

# The shuffle() method makes changes to the original array.

In [30]:
arr

array([3, 2, 5, 1, 4])

### Generating Permutation of Arrays

In [31]:
from numpy import random
import numpy as np

In [32]:
arr = np.array([1,2,3,4,5])

In [35]:
random.permutation(arr)

#The permutation() method returns a re-arranged array (and leaves the original array un-changed).

array([1, 3, 5, 2, 4])